### ISSUE TITLE
missing ^2 in "Introduction to Replication Success"?

### ISSUE THREAD

**Issue by ChristophGae** [crsuzh/ReplicationSuccess#76]
Hello @SamCH93 @florafauna @CharlotteMicheloud 

I've stumbled over the paragraph in the screenshot below, which is from [Introduction to ReplicationSuccess](https://cran.r-project.org/web/packages/ReplicationSuccess/vignettes/ReplicationSuccess.pdf)

Shouldn't it also be sigma_o^2 und sigma_r^2 for the first two sigma_o und sigma_r? the first two sigmas as well as the second two  sigmas are referred to as "squared standard errors".

Best regards and thanks for your great work! :-)
Christoph Gäbele

![2022-08-02_16h46_51](https://user-images.githubusercontent.com/40871114/182405328-c02a1641-dd0f-410f-ac37-d0dd69432cf7.png)

**Comment by felix-hof** [comment]
Thanks for the hint. We fixed this in the latest CRAN release.
